controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

Ex01Bundle:
    resource: '../src/Ex01Bundle/Controller'
    type: attribute

Ex02Bundle:
    resource: '../src/Ex02Bundle/Controller'
    type: attribute

D07Bundle:
    resource: '../src/D07Bundle/Controller'
    type: attribute
