parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'

    App\Service\Ex03Service: ~

    App\D07Bundle\Twig\Ex03Extension:
        arguments:
            - '@App\Service\Ex03Service'
        tags: ['twig.extension']
